config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'homes#index'
  resources :ingredients
  resources :ingredient_prices, only: %i[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/create_dish.rb
class CreateDish < ApplicationRecord
    validates :name, presence: true, uniqueness: true
end

app/models/dish.rb
# Class representing a dish in the application.
class Dish < ApplicationRecord
  has_many :ingredient_usages
  has_many :ingredients, through: :ingredient_usages

  validates :name, presence: true, uniqueness: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :ingredient_prices
  has_many :ingredient_usages
  has_many :dishes, through: :ingredient_usages
  has_many :ingredient_quantities
  accepts_nested_attributes_for :ingredient_prices

  validates :name, presence: true, uniqueness: true

  scope :available, -> { joins(:ingredient_quantities).where('ingredient_quantities.quantity > 0') }
end

app/models/ingredient_price.rb
class IngredientPrice < ApplicationRecord
  belongs_to :ingredient
end

app/models/ingredient_quantities.rb
class IngredientQuantity < ApplicationRecord
    belongs_to :ingredient
    validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
    validates :measurement_type, presence: true
end

app/models/ingredient_quantity.rb
# Class to register quantities for ingredients
class IngredientQuantity < ApplicationRecord
  belongs_to :ingredient
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :measurement_type, presence: true
end

app/models/ingredient_usage.rb
# Class representing an ingredient usage in the application.
class IngredientUsage < ApplicationRecord
  belongs_to :dish
  belongs_to :ingredient
end

app/controllers/application_controller.rb
require 'prometheus/client'

class ApplicationController < ActionController::Base
  CONTROLLER_CALLS = Prometheus::Client::Counter.new(:controller_calls_total,
                                                     docstring: 'Total number of controller calls', labels: %i[method path])

  def increment_request_count
    CONTROLLER_CALLS.increment(labels: { method: request.method, path: request.path })
    Prometheus::Client.registry.register(CONTROLLER_CALLS)
  end
end

app/controllers/homes_controller.rb
# Controller responsible for managing root.
class HomesController < ApplicationController
  def index; end
end

app/controllers/ingredient_prices_controller.rb
class IngredientPricesController < ApplicationController
  before_action :set_ingredient
  def new
    @ingredient_price = IngredientPrice.new
  end

  def create
    @ingredient_price = IngredientPrice.new(ingredient_price_params)
    if @ingredient_price.save
      redirect_to @ingredient_price, notice: 'Ingredient price was successfully created.'
    else
      render :new
    end
  end

  private

  def ingredient_price_params
    params.require(:ingredient_price).permit(:ingredient_id, :price, :source)
  end

  def set_ingredient
    @ingredients = Ingredient.all
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end

  def new
    flash[:notice] = 'Adicione ingrediente.'
    @ingredient = Ingredient.new
    @ingredient.ingredient_prices.build
  end

  def create
    @ingredient = Ingredient.new(name: ingredient_params[:name])

    respond_to do |format|
      if @ingredient.save
        format.turbo_stream do
          render turbo_stream: turbo_stream.append('ingredients_table', partial: 'ingredient_created',
                                                                        locals: { ingredient: @ingredient })
        end
        format.html { redirect_to(ingredients_url, notice: '#{ingredient.name} added.') }
      else
        # TODO: respond notice
        format.html { render :new, status: 422 }
      end
    end
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:id, :name, ingredient_prices_attributes: %i[id price source])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homes/index.html.erb
  
TESTE

app/views/ingredient_prices/_form.html.erb
<%= form_with(model: @ingredient_price, local: true) do |form| %>
  <% if @ingredient_price.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient_price.errors.count, "error") %> prohibited this ingredient_price from being saved:</h2>

      <ul>
      <% @ingredient_price.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ingredient_id %>
    <%= form.collection_select :ingredient_id, @ingredients, :id, :name, prompt: true %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :source %>
    <%= form.text_field :source %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ingredient_prices/new.html.erb
<h1>New ingredient price</h1>

<%= render "form", ingredient_price: @ingredient_price %>

<br>

<div>
  <%= link_to "Back to ingredient prices", ingredient_prices_path %>
</div>

app/views/ingredients/_ingredient_created.html.erb
<tr>
    <td><%= @ingredient.name %></td>
</tr>

app/views/ingredients/edit.html.erb
<%= turbo_frame_tag 'ingredient_frame' do %>
  <%= form_with model: @ingredient do |form| %>
      
        <div class="field">
          <%= form.label :name, 'Name' %>
          <%= form.text_field :name %>
        </div>
      Preços:
      <ul>
        <%= form.fields_for :ingredient_prices do |ingredient_prices_form| %>
          <li>
            <%= ingredient_prices_form.label :price %>
            <%= ingredient_prices_form.number_field :price %>
          </li>
          <li>
            <%= ingredient_prices_form.label :source %>
            <%= ingredient_prices_form.text_field :source %>
          </li>
        <% end %>
      </ul>
      <div class="actions">
          <%= form.submit %>
      </div>
    <% end %>
  <% end %>

app/views/ingredients/index.html.erb
<main class="flex flex-col gap-4">
  <h1>Ingredients</h1>
  <%= turbo_frame_tag 'ingredient_frame' do %>
    <div>
      <%= link_to "Add new ingredient", new_ingredient_path, method: :get, class: "bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded inline-flex items-center" %>
    </div>
  <% end %>
  <table>
    <thead>
      <tr>
        <th class="change">Name</th>
      </tr>
    </thead>
    <tbody id="ingredients_table">
      <% @ingredients.each do |ingredient| %>
        <tr>
          <td><%= ingredient.name %></td>
          <td><%= link_to "Add price", new_ingredient_price_path, method: :get, class: "bg-green-400 hover:bg-green-100 text-gray-800 font-bold py-2 px-4 rounded inline-flex items-center" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</main>

app/views/ingredients/new.html.erb
<%= turbo_frame_tag 'ingredient_frame' do %>
  <%= form_with model: @ingredient do |form| %>
    <div class="relative">
      <%= form.text_field :name, class: "border border-gray-300 rounded-md px-4 py-2 w-full placeholder-gray-400 focus:outline-none focus:border-indigo-500", placeholder: "Type here..." %>
      <%= form.submit "Submit", class: "absolute inset-y-0 right-0 px-4 py-2 bg-indigo-500 text-white rounded-r-md hover:bg-indigo-600 focus:outline-none" %>
    </div>
  <% end %>
  <!-- Showing flash -->
  <% if notice.present? %>
    <%= turbo_stream.replace "notices" do %>
      <p class="notice"><%= notice %></p>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Menu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-100">
    <p class="notice" id="notices"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render partial: 'shared/navbar' %>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="bg-white shadow">
  <div class="container mx-auto px-4">
    <div class="w-full flex flex-col py-4">
      <a class="text-xl font-bold text-gray-800" href="/">Food App</a>
      <div>
        <ul class="container flex justify-between">
          <li><a class="text-gray-800 hover:text-gray-600" href="/">Home</a></li>
          <li><a class="text-gray-800 hover:text-gray-600" href="/weekly_menu">Weekly Menu</a></li>
          <li><%= link_to "Ingredientes", ingredients_path %></li>
          <li><a class="text-gray-800 hover:text-gray-600" href="/food_stock">Food Stock</a></li>
          <li><a class="text-gray-800 hover:text-gray-600" href="/recipes">Recipes List</a></li>
        </ul>
      </div>
    </div>
  </div>
</nav>